# ===============================
# SERVER
# ===============================
quarkus.application.name=notification-service
quarkus.http.port=8083

# ===============================
# MYSQL
# Gi? database c? c?a b?n
# ===============================
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/notification_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
quarkus.datasource.username=${DB_USER:nguyenbavien}
quarkus.datasource.password=${DB_PASS:nguyenbavien}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.jdbc.timezone=Asia/Ho_Chi_Minh

quarkus.jackson.timezone=Asia/Ho_Chi_Minh

# ===============================
# MAIL
# ===============================
quarkus.mailer.from=${MAIL_USER:nguyenbavien.26092005@gmail.com}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=${MAIL_USER:nguyenbavien.26092005@gmail.com}
quarkus.mailer.password=${MAIL_PASS:tndrfrxeictyrbza}
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.mock=false

# ===============================
# RABBITMQ
# Spring c?:
# exchange: notifications-exchange
# queue: notifications.email.queue
# routing-key: notifications.email
# ===============================
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USER:guest}
rabbitmq-password=${RABBITMQ_PASS:guest}

mp.messaging.outgoing.notifications-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.notifications-out.exchange.name=notifications-exchange
mp.messaging.outgoing.notifications-out.exchange.type=topic
mp.messaging.outgoing.notifications-out.routing-key=notifications.email

mp.messaging.incoming.notifications-in.connector=smallrye-rabbitmq
mp.messaging.incoming.notifications-in.queue.name=notifications.email.queue
mp.messaging.incoming.notifications-in.exchange.name=notifications-exchange
mp.messaging.incoming.notifications-in.exchange.type=topic
mp.messaging.incoming.notifications-in.routing-keys=notifications.email
mp.messaging.incoming.notifications-in.auto-bind-dlq=false

# ===============================
# CORS n?u test tr?c ti?p 8083
# ===============================
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:5174
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

# ===============================
# LOG
# ===============================
quarkus.log.category."io.quarkus.mailer".level=DEBUG