# ===============================
# APPLICATION
# ===============================
quarkus.application.name=revenue-service
quarkus.http.port=8089

# ===============================
# REST CLIENTS
# Cart Service ch?y ? port 8088
# Order Service ch?y ? port 8084
# ===============================

# Cách config MicroProfile REST Client
cart/mp-rest/url=http://localhost:8088
order/mp-rest/url=http://localhost:8084

cart/mp-rest/connectTimeout=30000
cart/mp-rest/readTimeout=30000

order/mp-rest/connectTimeout=30000
order/mp-rest/readTimeout=30000

# Cách config Quarkus m?i, gi? thêm cho ch?c
quarkus.rest-client.cart.url=http://localhost:8088
quarkus.rest-client.order.url=http://localhost:8084

quarkus.rest-client.cart.connect-timeout=30000
quarkus.rest-client.cart.read-timeout=30000

quarkus.rest-client.order.connect-timeout=30000
quarkus.rest-client.order.read-timeout=30000

# ===============================
# CORS
# N?u g?i qua gateway thì ?? false.
# ===============================
quarkus.http.cors.enabled=false

# N?u mu?n FE g?i tr?c ti?p revenue-service thì b?t:
# quarkus.http.cors.enabled=true
# quarkus.http.cors.origins=http://localhost:5173
# quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
# quarkus.http.cors.headers=*
# quarkus.http.cors.access-control-allow-credentials=true

# ===============================
# LOGGING
# ===============================
quarkus.log.level=INFO
quarkus.log.category."org.anta.services.revenue_service".level=DEBUG