# ===============================
# SERVER
# ===============================
quarkus.http.port=8080
quarkus.application.name=gateway-service

# ===============================
# CORS - dùng custom CorsResponseNormalizationFilter
# ===============================
quarkus.http.cors.enabled=false

gateway.cors.allowed-origins=http://localhost:5173,http://localhost:5174
gateway.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
gateway.cors.allowed-headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
gateway.cors.exposed-headers=Authorization,X-User-Name,X-User-Role,Location
gateway.cors.allow-credentials=true
gateway.cors.max-age=3600

# ===============================
# JWT - ph?i gi?ng identity-service
# ===============================
gateway.jwt.secret=mysecretkeymysecretkeymysecretkey123

# ===============================
# OPEN PREFIXES - gi?ng gateway Spring Boot c?
# Nh?ng API này không c?n JWT ? gateway
# ===============================
gateway.security.open-prefixes=/api/auth,/api/user,/api/product,/api/products,/api/public,/api/cloud,/api/address,/api/orders,/api/cart,/api/carts,/api/payments,/api/momo,/api/categories,/api/dashboard,/api/staff,/actuator

# ===============================
# ROUTES
# Gateway port 8080
# Identity service port 8082
# Cloud service port 8081 n?u theo RouteConfig c? c?a b?n
# ===============================

gateway.routes[0].id=identity-auth
gateway.routes[0].prefix=/api/auth
gateway.routes[0].target=http://localhost:8082

gateway.routes[1].id=identity-user
gateway.routes[1].prefix=/api/user
gateway.routes[1].target=http://localhost:8082

gateway.routes[2].id=identity-address
gateway.routes[2].prefix=/api/address
gateway.routes[2].target=http://localhost:8082

gateway.routes[3].id=cloud-service
gateway.routes[3].prefix=/api/cloud
gateway.routes[3].target=http://localhost:8081

gateway.routes[4].id=notification-service
gateway.routes[4].prefix=/api/notifications
gateway.routes[4].target=http://localhost:8083


gateway.routes[5].id=product-service-product
gateway.routes[5].prefix=/api/product
gateway.routes[5].target=http://localhost:8086

gateway.routes[6].id=product-service-variant
gateway.routes[6].prefix=/api/productVariant
gateway.routes[6].target=http://localhost:8086

gateway.routes[7].id=product-service-reservations
gateway.routes[7].prefix=/api/reservations
gateway.routes[7].target=http://localhost:8086

gateway.routes[8].id=category-service
gateway.routes[8].prefix=/api/categories
gateway.routes[8].target=http://localhost:8087