# ===============================
# APPLICATION
# ===============================
quarkus.application.name=payment-service
quarkus.http.port=8085

# ===============================
# DATABASE
# ===============================
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/payment_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
quarkus.datasource.username=${DB_USER:nguyenbavien}
quarkus.datasource.password=${DB_PASS:nguyenbavien}

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQLDialect
quarkus.hibernate-orm.jdbc.timezone=Asia/Ho_Chi_Minh

# ===============================
# JACKSON
# ===============================
quarkus.jackson.timezone=Asia/Ho_Chi_Minh
quarkus.jackson.fail-on-unknown-properties=false

# ===============================
# CORS
# N?u g?i qua gateway thì false.
# N?u FE g?i tr?c ti?p payment-service thì b?t true.
# ===============================
quarkus.http.cors.enabled=false

# N?u mu?n g?i tr?c ti?p t? FE:
# quarkus.http.cors.enabled=true
# quarkus.http.cors.origins=http://localhost:5173
# quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
# quarkus.http.cors.headers=*
# quarkus.http.cors.access-control-allow-credentials=true

# ===============================
# ORDER SERVICE
# ===============================
order.service.url=http://localhost:8084

# ===============================
# MOMO CONFIG
# ===============================
momo.partner-code=${MOMO_PARTNER_CODE:MOMO}
momo.access-key=${MOMO_ACCESS_KEY:F8BBA842ECF85}
momo.secret-key=${MOMO_SECRET_KEY:K951B6PE1waDMi640xX08PD3vg6EkVlz}
momo.return-url=http://localhost:5173/momo-return
momo.end-point=https://test-payment.momo.vn/v2/gateway/api
momo.ipn-url=http://localhost:8085/api/momo/ipn-handler
momo.request-type=captureWallet

# API c? trong PaymentService dùng ?? check-status
momo.check-status-url=https://api.momo.vn/check-payment-status

# ===============================
# QUARKUS REST CLIENT
# configKey trùng v?i @RegisterRestClient(configKey = "...")
# ===============================
quarkus.rest-client.momo.url=${momo.end-point}
quarkus.rest-client.order-service.url=${order.service.url}

quarkus.rest-client.momo.connect-timeout=30000
quarkus.rest-client.momo.read-timeout=30000
quarkus.rest-client.order-service.connect-timeout=30000
quarkus.rest-client.order-service.read-timeout=30000

# ===============================
# LOGGING
# ===============================
quarkus.log.level=INFO
quarkus.log.category."org.anta.payment_service".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE