# ===============================
# SERVER
# ===============================
quarkus.application.name=category-service
quarkus.http.port=8087

# ===============================
# MYSQL
# ===============================
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/category_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
quarkus.datasource.username=${DB_USER:nguyenbavien}
quarkus.datasource.password=${DB_PASS:nguyenbavien}

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.jdbc.timezone=Asia/Ho_Chi_Minh

quarkus.jackson.timezone=Asia/Ho_Chi_Minh

# ===============================
# PRODUCT SERVICE
# Spring c?: product.service.url
# Product service c?a b?n ch?y 8086
# ===============================
product.service.url=http://localhost:8086/api/product

# ===============================
# CORS n?u g?i tr?c ti?p category-service
# N?u ?i qua gateway thì gateway x? lý chính
# ===============================
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:5174
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
quarkus.http.cors.exposed-headers=Authorization,Content-Type,Location
quarkus.http.cors.access-control-allow-credentials=true