quarkus.http.port=8084

quarkus.application.name=order-service

# DATABASE
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/order_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
quarkus.datasource.username=${DB_USER:nguyenbavien}
quarkus.datasource.password=${DB_PASS:nguyenbavien}

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQLDialect

# timezone
quarkus.hibernate-orm.jdbc.timezone=Asia/Ho_Chi_Minh

# LOG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
quarkus.log.category."org.anta".level=DEBUG

# REST CLIENTS
product-reservation/mp-rest/url=http://localhost:8086/api/reservations
payment/mp-rest/url=http://localhost:8085/api/payments
product/mp-rest/url=http://localhost:8086

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.access-control-allow-credentials=true